/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.diu.bd.studentrecordsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Sabbir
 */
public class LoginForm extends javax.swing.JFrame {

    private final Repository repo;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        repo = new Repository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        user_name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        root_panel.setBackground(new java.awt.Color(102, 102, 102));
        root_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN TO CONTINUE");
        root_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 350, 50));
        root_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, 10));
        root_panel.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, -1));
        root_panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 370, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("User Name");
        root_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 20));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password");
        root_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 20));

        login_btn.setText("LOGIN");
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        root_panel.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, -1));

        create_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sabbir\\Downloads\\Top Secret\\image\\Delete_25px.png")); // NOI18N
        create_btn.setText("CREATE ACCOUNT");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });
        root_panel.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sabbir\\Downloads\\students.png")); // NOI18N
        root_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        getContentPane().add(root_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        setSize(new java.awt.Dimension(716, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        // TODO add your handling code here:
        var username = user_name.getText();
        var pass = password.getText();

        if (!username.isEmpty() && !pass.isEmpty()) {
            boolean res = repo.selectStudentRecord(username, pass);
            System.out.println("Result: " + res);
            if (res) {
                new StudentInfoForm().setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Username or password is not correct");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Username or password can not be empty");
        }
    }//GEN-LAST:event_login_btnMouseClicked

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        // TODO add your handling code here:
        new SignUpForm().setVisible(true);
    }//GEN-LAST:event_create_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel root_panel;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables

}
